[package]
name = "actix-web-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.1.0"
serde = "1.0.144"
dotenv = "0.15.0"
futures = "0.3.23"
env_logger = "0.7"

mongodb = "2"




